version: '3.5'

services:

  web-app:
    container_name: web-app
    build:
      context: ./web-app
      dockerfile: Dockerfile
    volumes:
      - ./web-app/src:/usr/src/app/src
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - web-app:web-app
    ports:
      - 80:80
      